export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  INVOICE_ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS",
  PAYMENT_DUPLICATE: "PAYMENT_DUPLICATE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROOM_NOT_AVAILABLE: "ROOM_NOT_AVAILABLE",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
