// Legacy tests type-only stub; not for runtime use
declare module "@/interface/errors/error-codes" {
  export const ErrorCodes: {
    VALIDATION_ERROR: "VALIDATION_ERROR"
    TENANT_NOT_FOUND: "TENANT_NOT_FOUND"
    INVOICE_ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS"
    PAYMENT_DUPLICATE: "PAYMENT_DUPLICATE"
    INTERNAL_ERROR: "INTERNAL_ERROR"
    ROOM_NOT_AVAILABLE: "ROOM_NOT_AVAILABLE"
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED"
    UNAUTHORIZED: "UNAUTHORIZED"
    FORBIDDEN: "FORBIDDEN"
  }
  export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
  export const ErrorStatus: {
    VALIDATION_ERROR: 400
    TENANT_NOT_FOUND: 404
    INVOICE_ALREADY_EXISTS: 409
    PAYMENT_DUPLICATE: 409
    INTERNAL_ERROR: 500
    ROOM_NOT_AVAILABLE: 409
    RATE_LIMIT_EXCEEDED: 429
    UNAUTHORIZED: 401
    FORBIDDEN: 403
  }
}
